baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Docker Test'
enableGitInfo = true

[frontmatter]
lastmod = [':git']

[[module.imports]]
path = "github.com/jmooring/hugo-content"
